//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "actor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub actor_id: i32,
    pub name: Option<String>,
    pub surname: Option<String>,
    pub role: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::performance_actors::Entity")]
    PerformanceActors,
}

impl Related<super::performance_actors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerformanceActors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
