//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Deserialize, serde::Serialize)]
#[sea_orm(table_name = "performance_actors")]
pub struct Model {
    pub actor_actor_id: i32,
    pub performance_performance_id: i32,
    pub amount: Option<i32>,
    #[sea_orm(primary_key)]
    pub actors_perfor_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor22,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor21,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor20,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor19,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor18,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor17,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor16,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor15,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor14,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor13,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor12,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor11,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor10,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor9,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor8,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor7,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor6,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor5,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor4,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor3,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor2,
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor1,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance22,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance21,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance20,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance19,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance18,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance17,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance16,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance15,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance14,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance13,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance12,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance11,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance10,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance9,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance8,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance7,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance6,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance5,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance4,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance3,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance2,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance1,
}

impl ActiveModelBehavior for ActiveModel {}
