//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "performance_actors")]
pub struct Model {
    pub actor_actor_id: i32,
    pub performance_performance_id: i32,
    pub amount: Option<i32>,
    #[sea_orm(primary_key)]
    pub actors_perfor_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::actor::Entity",
        from = "Column::ActorActorId",
        to = "super::actor::Column::ActorId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Actor,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformancePerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance,
}

impl Related<super::actor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Actor.def()
    }
}

impl Related<super::performance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Performance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
