//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "play")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub play_id: i32,
    pub title: Option<String>,
    pub author: Option<String>,
    pub director: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::performance::Entity")]
    Performance,
}

impl Related<super::performance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Performance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
