//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Deserialize, serde::Serialize)]
#[sea_orm(table_name = "poster")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub poster_id: i32,
    pub performance_id: Option<i32>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance23,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance22,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance21,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance20,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance19,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance18,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance17,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance16,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance15,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance14,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance13,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance12,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance11,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance10,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance9,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance8,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance7,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance6,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance5,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance4,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance3,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance2,
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance1,
}

impl ActiveModelBehavior for ActiveModel {}
