//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "theater")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub theater_id: i32,
    pub name: Option<String>,
    pub address: Option<String>,
    pub capacity: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::stage::Entity")]
    Stage,
}

impl Related<super::stage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
