//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Deserialize, serde::Serialize)]
#[sea_orm(table_name = "ticket")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub ticket_id: i32,
    pub performance_id: Option<i32>,
    pub seat_number: Option<i32>,
    pub date: Option<Date>,
    pub cost: Option<i32>,
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation, serde::Deserialize, serde::Serialize)]

pub enum Relation {
    #[sea_orm(
        belongs_to = "super::performance::Entity",
        from = "Column::PerformanceId",
        to = "super::performance::Column::PerformanceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Performance,
    #[sea_orm(has_many = "super::viewer_ticket::Entity")]
    ViewerTicket,
}

impl Related<super::performance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Performance.def()
    }
}

impl Related<super::viewer_ticket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ViewerTicket.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
