//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Deserialize, serde::Serialize)]
#[sea_orm(table_name = "viewer_ticket")]
pub struct Model {
    pub viewer_viewer_id: i32,
    pub ticket_ticket_id: i32,
    pub bought_date: Option<Date>,
    #[sea_orm(primary_key)]
    pub vi_ti_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket22,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket21,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket20,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket19,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket18,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket17,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket16,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket15,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket14,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket13,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket12,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket11,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket10,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket9,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket8,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket7,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket6,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket5,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket4,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket3,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket2,
    #[sea_orm(
        belongs_to = "super::ticket::Entity",
        from = "Column::TicketTicketId",
        to = "super::ticket::Column::TicketId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ticket1,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer22,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer21,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer20,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer19,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer18,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer17,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer16,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer15,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer14,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer13,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer12,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer11,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer10,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer9,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer8,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer7,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer6,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer5,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer4,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer3,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer2,
    #[sea_orm(
        belongs_to = "super::viewer::Entity",
        from = "Column::ViewerViewerId",
        to = "super::viewer::Column::ViewerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Viewer1,
}

impl ActiveModelBehavior for ActiveModel {}
